### ISSUE TITLE
To move the router login to new Controlles folder

### ISSUE THREAD

**Issue by SOUMOJIT-CHAKRABORTY** [aniket22n/google-drive-clone#3]
Hey! I think we should move the logic from the routers folder to controllers folder for better abstraction

**Comment by aniket22n** [comment]
that's good,
If you really think this is going to be helpful implement it and make a PR

**Comment by SOUMOJIT-CHAKRABORTY** [comment]
Okay

**Comment by ThFate07** [comment]
can you do this ? @SOUMOJIT-CHAKRABORTY

**Comment by ThFate07** [comment]
can you handle this? @SOUMOJIT-CHAKRABORTY

**Comment by ThFate07** [comment]
ooh, you already made the pr
